pipeline:
  identifier: Build_sanket_qp_azure_services_tests_1706741944031
  name: Build azure-services-tests
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: sanket-qp/azure-services-tests
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    shell: Sh
                    command: echo hello world
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: Install Dependencies
                  identifier: Install_Dependencies
                  spec:
                    shell: Sh
                    command: poetry install
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
    - stage:
        name: postprovision
        identifier: postprovision
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: Run PostProvision Script
                  identifier: Run_PostProvision_Script
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: cd postgres-flex && pytest
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
            rollbackSteps: []
          serviceDependencies: []
        tags: {}
    - stage:
        name: Run Tests
        identifier: Run_Tests
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: cd postgres-flex && pytest
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
